name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set +x
        if git branch --contains "${{github.ref_name}}" main | grep -q "main"; then
          
          echo "Release:     ${{github.ref_name}}" >  version.txt
          echo "GitHub repo: ${{github.repository}}">> version.txt
          echo "SHA1:        ${{github.sha}}" >> version.txt

          cat version.txt
          
          gh release create "${{github.ref_name}}" --generate-notes --verify-tag --latest >> $GITHUB_STEP_SUMMARY
          gh release upload ${{github.ref_name}} version.txt

          cat version.txt >> $GITHUB_STEP_SUMMARY

          echo Use gh CLI to download the release >> $GITHUB_STEP_SUMMARY 
          echo \`\`\`shell >> $GITHUB_STEP_SUMMARY 
          echo. gh release download ${{github.ref_name}} -p 'version.txt' && gh release download ${{github.ref_name}} --archive tar.gz >> $GITHUB_STEP_SUMMARY
          echo \`\`\`>> $GITHUB_STEP_SUMMARY 


        else

          echo "Tag ${{github.ref_name}} is not on main, skipping release creation."
          exit 1

        fi